# Generated by Django 2.1.4 on 2018-12-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20181229_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateField(),
        ),
    ]
